# Generated by Django 5.0.6 on 2024-05-12 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_producttype_product_type_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_settings', serialize=False, to='product.admin')),
                ('date_min', models.IntegerField(blank=True, null=True)),
                ('percent_min', models.PositiveIntegerField(blank=True, default=True)),
                ('data_max', models.IntegerField(blank=True, null=True)),
                ('percent_max', models.PositiveIntegerField(blank=True, default=True)),
            ],
            options={
                'verbose_name': 'AdminSettings',
            },
        ),
    ]
