# Generated by Django 5.0.6 on 2024-05-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_adminsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='count_max',
            field=models.PositiveIntegerField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='count_min',
            field=models.PositiveIntegerField(blank=True, default=True),
        ),
    ]
