# Generated by Django 5.0.6 on 2024-05-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_marketupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='write_off_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
