# Generated by Django 5.0.6 on 2024-05-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_adminsettings_write_off_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='minimum_quantity_of_goods',
            field=models.PositiveIntegerField(blank=True, default=7),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='count_max',
            field=models.PositiveIntegerField(blank=True, default=7),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='count_min',
            field=models.PositiveIntegerField(blank=True, default=7),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='data_max',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='date_min',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='percent_max',
            field=models.PositiveIntegerField(blank=True, default=7),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='percent_min',
            field=models.PositiveIntegerField(blank=True, default=7),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='write_off_date',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
    ]
