# Generated by Django 5.0.6 on 2024-05-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_14052024_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_product',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
